version: '3.8'

services:
  frontend:
    depends_on:
      - backend
    image: frontend
    container_name: front-end
    build:
      context: ./client
    volumes:
      - ./client/app/src/:/app/src
    ports:
      - 5000:4000
    env_file:
      - .env
  backend:
    depends_on:
      - postgres
    image: backend
    container_name: back-end
    build:
      context: ./server
    env_file:
      - .env
    volumes:
        - ./server/app/src/:/app/src
    ports:
      - 8000:3000
      - 5555:5555
  postgres:
    image: postgres:latest
    container_name: db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
