version: '3.8'

services:
  frontend:
    depends_on:
      - backend
    image: frontend
    container_name: front-end
    build:
      context: ./frontend
    ports:
      - 8000:80
    volumes:
      - ./frontend/app/src:/app/src
  backend:
    depends_on:
      - postgres
    image: backend
    container_name: back-end
    build:
      context: ./backend
    env_file:
      - .env
    volumes:
        - ./backend/app/src/:/app/src
  postgres:
    image: postgres:latest
    container_name: db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
